dunst-project/dunst

README.pod, notification.c, settings.c, settings.h
Adds option always_run_script.
If set to true, scripts defined by a rule will always be executed, even if the format is set to "" to suppress the notification.
Niche, but useful when a user wants an action triggered by an application's notification but doesn't want the actual notification (see issue 212).
Please excuse my being bad at git.
=> Add option to always run script (even for suppressed notifications)

x.c
I made the text center when the icon is bigger than the text:
This should solve issue #152.
I also edited the way the frames are drawn and the padding is made, with the current behavior icons are not padded correctly when they are bigger than the text (they appear too low and can even overflow out of the window if there is no padding).
With those edits, the icon will appear centered if it's bigger than the text, as shown in the picture above.
**Edit:**
Here is more explanation for why padding should be edited and how it is related to centering. With the current situation, the padding is very inconsistent when having multiple notifications, the separators are taken into account, but not the frame.
Making the padding internal to the frame (like with CSS borders), and not overlapping with …
=> Vertical centering and padding

src/rules.c
With `n->icon = r->new_icon` and later `free(n->icon)`, `r->new_icon` is wrongly freed. Fix that with strdup.
Also fix an obvious memory leak by the way.
Intended to fix #281.
=> Fix #281 bad free. Also fix a memory leak.

src/dbus.c
`value` was already being freed by `g_dbus_method_invocation_return_value`.
Fixes #215
=> Fix a double free in on_get_capabilities.

src/dbus.c, src/dbus.h, src/dunst.c, src/dunst.h, src/menu.c, src/menu.h, src/notification.c, src/notification.h, src/option_parser.c, src/option_parser.h, src/rules.c, src/rules.h, src/settings.c, src/settings.h, src/utils.c, src/x.c, src/x.h
1. Fix `#include`s.
2. Use only glib functions for memory management. Don't mix with stdlib
3. Fix a missing `*` in option_parser.c
There are lots of of changes and I wasn't sure if it would be a good pull request, but I was invited by a maintainer.
I know there are conflicts, but I'm busy this week and do not have time to resolve them.
=> Fix `#include`s and use only glib for memory management

Makefile
Show what is happening during build etc, the way most other make-based
projects do.
There is thus no need for the options target. Additionally, this target
caused unnecessary rebuilds of ./dunst each and every time, even on
`make install`.
=> Makefile: just be verbose

org.knopwob.dunst.service.in
This should have no effect on systems without systemd; it just causes dunst to be started through systemd when possible.
=> Allow dunst to be managed by systemd

contrib/dunst.systemd.service.in
* Add `Documentation` field.
* Make it `WantedBy` `default.target` (`multi-user.target` isn't a valid user target).
* Make it a dbus unit (consider it active when it acquires the dbus interface).
=> Modernize the systemd unit a bit

src/notification.c
This was originally submitted as #125, but it ended up being incorporated into #204, which was merged instead of my version. That's fine.
However, later, commit 3ef1506 (presumably accidentally) reverted back to the pre-#204 behavior.
So this PR re-applies that change.
=> Expand "\\n" to "\n" in the format string only; not message text.

src/option_parser.c
Usually, it's "Warning: invalid config file at line %d", but in one case there's a colon after "line".
I noticed this while working on #298.
=> option_parser: Fix inconsistent Warning message.

src/notification.c, src/option_parser.c, test/data/test-ini, test/option_parser.c
This is an updated version of #126 (2013).
The current behavior is
- If the value contains a double-quote:
- 1. Verify that it must contains at least two quotes.
- 2. If one of the quotes is the first character, trim it.
- 3. If one of the quotes is the last character, trim it.
- Else:
- 1. Trim a trailing comment from the value.
This has the effect that
`key = "value" # comment` => `value " #comment`
This is surprising and almost certainly not what the user wants.
However, it allows simple nested quotes like:
`key = "A string "with quotes""` => `A string "with quotes"`
Adjust the brokenness of the first example at the expense of breaking the
second.  A user seeking that value will now have to type:
key = "A string \"with quotes\""
=> option_parser: Allow comments on lines with quoted strings

src/markup.c, src/markup.h, src/notification.c, src/notification.h, src/x.c, test/markup.c, test/test.c
This has 4 commits: The first two tidy and reorganize the markup handling without making any functional changes. The last two commits each fix an issue with the markup handling that is now easy-to-spot in the reorganized code.
There are two user-visible changes here.  In one case, the behavior is straight-up a bug, and fixing it is OK.  In the other case, it improves the error-handling behavior; since an error is encountered anyway (and it says so on stdout), I believe that a change in behavior is fair game.  That is, I believe that this can be merged in to `master`, rather than `next`.
=> Tidy and fix markup handling.

src/settings.c, src/settings.h, src/x11/x.c
It seems from XParseGeometry documentation, that it's valid to have `=` sign as first character of spec, but it's not documented how it's handled. So, I propose to use `=` at the geometry spec as indicator, that notification window should be positioned in the center of monitor (if both X and Y offsets are 0). It makes possible to align notification windows so they are shown at the X-center of active monitor by specifying geometry like `=<width>x<height>+0-40` — display notification window at the X-center of monitor and 40 px from bottom.
=> Add centering to -geometry flag

Makefile, contrib/dunst.systemd.service.in
Hardcoding a DISPLAY variable is a bad idea because it means that dunst
will only run on X11, and only for that specific configuration.
FWIW, this actually applies to any desktop app run via systemd:
1. `DISPLAY` should be set by `systemctl --user set-environment` elsewhere.
2. `DISPLAY=:0` is not universally valid.
3. This breaks dunst if attempting to run wayland, and requires manually
starting it (eg: not via systemd), or editing the file.
See [this comment](https://github.com/dunst-project/dunst/issues/314#issuecomment-300527201) for context.
=> Tweak systemd.service

docs/dunst.pod, src/menu.c, src/menu.h, src/notification.c, src/notification.h, src/x11/x.c
A middle click on a notification with a single or default action will
invoke it. If there are multiple actions and no default, the context
menu is opened. If there are no actions, proceed similarly with URLs.
As discussed in #234.
I decided to always prioritize actions over URLs, since that seems more likely to be what the user wants.
=> Allow middle click on notification to invoke action

CHANGELOG.md, src/notification.c, src/notification.h
This would be my 2 cents to fix #248 and remove the last blocker to have a new release.
This PR adds the option `max_fieldlength` to have a maximum of specific chars per field. So overlong messages will get truncated to the specified length.
Also if it's not wanted to have a limit, a minus-value can be chosen to skip the cutting.
I'm not sure yet, what a reasonable default would be. I've used `100`, but I'd like to have other's opinions here. Alternatively `-1` (=> no limit) would also be a good default.
=> limit length of single fields in notification

config.def.h, docs/dunst.pod, dunstrc, src/settings.c, src/settings.h, src/x11/x.c
This bothered me.
I replaced all the instances of 'folder' with 'path'.
I tested the icon functionality and it worked, including the relevant configuration option; but please somebody else also look at it because I'm unfamiliar with the code.
=> replace 'folder' with 'path' in icon functionality

.travis.yml, Makefile, README.md, config.mk
in #263 there was mentioned to depend on gtk3 instead of gtk2. Mainly this is only incrementing the number, as it seems to work so far. Further testing **is** needed.
Edit: seen, that there's already an issue open: #327
=> depend on gtk3 instead of gtk2

src/dunst.c
Print out the full usage on STDERR. Currently only the string `usage` gets printed there, but not the other stuff. This is stupid.
=> print usage only on stdout

src/dbus.c
The desktop notification spec version 1.1 used "image_data" instead of "image-data" as the key for raw icons. This is still used in some applications, e.g., in the [Clementine music player](https://github.com/clementine-player/Clementine/blob/42aafd247a3a96f7a6c07d31b3a0881691a8daf2/src/widgets/osd_x11.cpp#L111).
=> parse raw icons from the (deprecated) image_data attribute

src/dunst.c
When closing a notification in check_timeouts, `iter` will get removed of the list and therefore `iter->next` is not available at the end of the loop anymore. This requires calling check_timeouts again.
Introducing the `nextiter` pointer, which will save `iter->next` in advance, solves this problem and does not require traversing the already traversed part of the list again.
=> handle removing of elements in GList correctly

src/notification.c
Implicitly declared basename() makes dunst dump core on FreeBSD 11.1 (in src/notification.c:209)
=> Add libgen.h include and guard against basename(3) modifying its arg

docs/dunst.pod, src/option_parser.c, src/option_parser.h, src/settings.c, src/utils.c, src/utils.h, test/data/test-ini, test/option_parser.c, test/utils.c
wordexp replaces all variables and `~` in the string. TBH I don't quite like the thing, that it replaces all variables, but there is no other way.
Fixes #350
=> replace variables and ~ in script paths

src/x11/x.c
If the svg-file is not found, the string containing the svg ending is never freed again.
=> Fix memory leak in get_pixbuf_from_path

src/dbus.c, src/dbus.h, src/menu.c, src/notification.c, src/notification.h, src/option_parser.c, src/rules.c, src/rules.h, src/settings.c, src/utils.c, src/utils.h, src/x11/screen.c, src/x11/x.c, src/x11/x.h
As @tsipinakis mentioned in #365 ([here](https://github.com/dunst-project/dunst/pull/365#discussion_r137354820)), this unifies all pointer declarations.
To achieve a consistent scheme, all stars of the pointers should be on the side of the variable and not on the side of the type.
wrong: `char* a`
wrong: `char * a`
good:  `char *a`
This commit is generated by the following sed command with manual fixes of all false positives.
```
find src \( -name '*.c' -or -name '*.h' \) -print0 | xargs -0 -n1 sed -i 's/\([a-zA-Z]\+[-_a-zA-Z0-9]*\)\s*\*\s\+\([a-zA-Z]\+[-_a-zA-Z0-9]*\)/\1 *\2/g'
```
=> Refactor star scheme of pointers

CHANGELOG.md, config.def.h, docs/dunst.pod, dunstrc, src/dbus.c, src/dunst.c, src/notification.c, src/notification.h, src/rules.c, src/rules.h, src/settings.c
transient notifications. #310 
- ignore notification automatically in history
- remove notification from stack, even if X is idle.
=> add support for transient hints

CHANGELOG.md, docs/dunst.pod, dunstrc, src/notification.c, src/notification.h, src/utils.h, test/notification.c
To replace all occuring format strings inside the msg, replace_all had
been used previously. This leads to buggy behavior, if a format string
occurs in the replaced text, as the format string will get replaced
again under certain conditions.
Introducing a pointer, which skips the already replaced parts, will
prevent doubly replacing format strings from content.
Fixes #322
=> Prevent replacement of format strings in message

Makefile
so that dunst binaries build in a reproducible way
in spite of indeterministic filesystem readdir order
See https://reproducible-builds.org/ for why this is good.
Note: the same change could be applied to the test/test part
but that does not end up in the (openSUSE) package so does not matter as much.
=> Sort linker input file list

src/option_parser.c
```
-history_length (double)                 - Max amount of notifications kept in history
```
vs:
```
-history_length (int)                    - Max amount of notifications kept in history
```
=> Rename double to int

CHANGELOG.md, docs/dunst.pod, dunstrc, src/settings.c, src/settings.h, src/x11/x.c
Add the option `ellipsize` to be able to select how the truncated lines should be ellipsized, accepting `start`, `middle` and `end`.
`middle` is the default value to not change the current behaviour.
`start` is maybe useless as it removes the "summary", but who knows.
`end` is useful to not ellipsize the (long) summary (e.g. IRC notifications where the summary (and/or the start of the body) contains "IRC", the user, and the server/channel).
=> Add option to control how to ellipsize truncated lines

dunstrc
Teeny follow-up to #374 to add possible values to `dunstrc`.
=> Add possible values for `ellipsize` to dunstrc

src/dunst.c, src/option_parser.c, src/option_parser.h, src/settings.c, test/option_parser.c
Although there had been some other fails in #379 , this [specific one](https://github.com/dunst-project/dunst/pull/379#discussion_r140561352) would not have happened. There are some methods doing different almost the same stuff (e.g.: `get_value` and `option_get_(string|int|...)`, which return from the config, but there is no easy visible rationale, which returns a duplicated element and which the original.
This PR strictly marks every constant argument as `const` to make it easier to understand the program and retrace the stuff. Additionally, the compiler can verify, that the original values are `const` everywhere, while the duplicated ones not.
=> Option parser const args

config.def.h, src/settings.c
Get the default value for `ellipsize` from `config.h`, instead of setting it in two different places (in case it is not set, and in case its value is invalid).
=> Use config.h for default ellipsize value

src/settings.c
Actually, this is the smallest memory leak, dunst currently has. But nevertheless, it shows up in valgrind's log.
=> Fix small memory leak

src/notification.c, src/notification.h
Previously, notifications had been replaced by removing the notification
out of the displayed/queue lists, redrawing the window and then adding
the new notification into the queue. This produced a flickering in
dunst.
By avoiding the overhead of closing and opening the window (simply
replacing the datapointer of the list), the flickering disappears.
Fixes #320
=> Replace notifications flickerless

src/notification.c, src/utils.c, test/utils.c
This is somewhat unrelated to previous PRs, but during test runs it bugged me, that this single skipped test was there.
Additionally, I made the `string_append` function also respect empty strings and concatenate the separator only, if both values are set.
=> Tests for string append

src/notification.c
Redo #354, as it got pushed out in #365
=> Work around non-gnu basename implementations

config.def.h, docs/dunst.pod, src/dbus.c, src/dunst.c, src/notification.c, src/notification.h, src/option_parser.c, src/option_parser.h, src/rules.h, src/settings.c, src/settings.h, src/utils.c, src/utils.h, src/x11/x.c, test/utils.c
Timeout in milliseconds and do not make rounding errors. Additionally use the monotonic time instead of `time(NULL)`, which is vulnerable to timeshifts.
To do:
- <del>add an option `option_get_time`, which allows timespans of `1ms`, `1s`, `1m`  to have variable timeout parameters (currently this is quickfixed via hardcoded `[...] = 1000 * 1000 * option_get_int( [...]`  </del> Done.
- <del>what's the workload, when x_is_idle and timeout = 1ms of notification?</del>
- <del>obviously, dunst is not that fast. I think we should add a minimal threshold</del>
- <del>bug: show age_threshold time does not increment in evenly spaced values.</del>
- really solved, but the age_threshold is always a second behind. The problem is somewhere else in `notification_update_text_to_render`.
Fixes #291
=> Timeout in msecs

src/dunst.c, src/markup.c, src/menu.c, src/notification.c, src/option_parser.c, src/utils.c
After some research, the _GNU_SOURCE does not affect any function call
anymore. To avoid future failures on other systems not using glibc,
_GNU_SOURCE gets removed.
---
To answer my own question:
> So, how can we require POSIX.1-2008?
I had the wrong mindset about this. There is no dynamic check for different versions of  functions. Also these do not change over time. So you simply don't check for this in your code. Either the function is defined (and then POSIX.1-2008 compatible) or the function is not defined (then it's not POSIX.1-2008) and the code does not compile. So dunst never runs with a wrong libc.
Fixes #359
=> Remove _GNU_SOURCE macro

dunstify.c
The notification object should actually get freed by notify_uninit. But
before freeing the notification, notify_uninit also sends the
CloseNotification signal directly, if the timeout is 0.
But the timeout of 0 should actually indicate a notification, which
never expires.
Fixes #415
=> Free notification before closing

.travis.yml, Makefile, config.mk
To improve code quality, treat warnings in travis now as fatal. This forces better code quality in PRs. Additionally dunstify is built there.
Introduces two build types (debug/release). This will become quite handy when we introduce logging and have a macro for debug messages, which gets activeted by setting a flag.
The makefile got restructured to have clearer structure and splitting of `config.mk` and `Makefile`.
=> Buildstack

CHANGELOG.md, src/dbus.c
Fixes #397 
Fixes #251 
`g_variant_lookup_value` will reference the GVariant. So we have to unref it again. This results, that every hint of the DBus message does not get freed upon `g_dbus_method_invocation_return_value`. This especially heavy for notifications sent with an attached icon.
---
Why also #251?
I see there are problems with dunst and probably this is not fixed fully. <del>I still get in the regions > 50 MB.</del> But spotify is the candidate, which sends raw icons.
(Also spotify replaces its notifications. The old notification does not get freed. This is fixed in #411)
=> Unref GVariants after use again

src/dbus.c, src/dunst.c, src/dunst.h, src/menu.c, src/notification.c, src/notification.h, src/queues.c, src/queues.h, src/x11/x.c
Ok, I'm done with the queue refactoring.
- Every part about accessing a `GQueue` is now handled in `queues.c`.
- All methods handling a queue are prefixed with `queues_` to resemble the namespace.
- The three queues have unique names `waiting`, `displayed`, `history`.
- All stuff in `notification_init` about closing notifications is removed
- to `dbus.c`: command pause/resume interpretation
- to `queues.c`: duplicates stacking
The refactoring about splitting `notification_init` is still to be done, but not part of this PR.
Mostly, I have split the stuff into two commits (the first one plain moving code from `file.c` to `queues.c` and the second one renaming/refactoring).
All commits compile without warnings.
Albeit most of the commits are plain refactoring, two commits stand out and may …
=> Refactor queues

src/dbus.c, src/dunst.c, src/notification.c, src/notification.h
This uses `-1` for to represent unset in the progress field. Semantically it makes no sense setting the progress to `0` to have it disabled.
---
rationale:
I personally would also like to have for every field an explicit representation for "unset". In a follow up PR I want to make `notification_create` to alloc the memory and *also* set all fields the unset representation. And `notification_init` defaults them.
So the code should look like this:
```
notification *n = notification_create();
//set only needed parameters
n->summary = "asdf";
notification_init(n);
```
Currently `notification_init` overwrites some fields without checking anything.
=> Use '-1' for undefined progress

config.mk, src/x11/screen.c
Due to the way Xlib handles errors XRRGetMonitors will cause dunst to exit if
the server doesn't support version 1.5 of Randr. The check for null is
effectively dead code. Change the code to fetch the Randr version and fallback
if the version is less than 1.5 when getting monitors.
=> Fix handling of non V1.5 XRandr.

src/queues.c, src/queues.h
Notifications marked with `history_ignore = 1` (and therefore transient ones too) are currently never freed.
=> Free notifications ignored in history

dunstify.c
Print the notification id, if requested, before blocking to catch action
return or NotificationClosed signal since once of those events happens
the program will exit without further action, bypassing the id printing
logic.
=> Dunstify: Print id before blocking

dunstify.c
If specifying --icon with UTF-8 characters, the g_option_context_parse
fails with an invalid byte conversion. The solution is to set the locale
explicitly.
For more info, see the GLib issue tracker:
https://bugzilla.gnome.org/show_bug.cgi?id=737137
Fixes #443
=> Set Locale in dunstify

src/dbus.c
As GApplications expose their icon via image-path hint and not via the
actual app_icon field, GApplication icons haven't been displayed before.
According to the notification spec, image-path hint should also override
the app_icon as follows:
1. image-data hint
2. image-path hint
3. app_icon parameter
=> Support image-path hint

src/dunst.c, src/dunst.h, src/x11/x.c
Notifications did not get undisplayed under certain conditions.
When sending two notifications simultaneously, both notifications get closed properly, but the shorter one gets undisplayed when  the longer one vanishes.
Fixes #433 
When sending notifications in this order: a long one, a short one and a middle one. Then there is no timeout for the middle one created, because there is an existing timeout and the timeout for the short notification fires faster. Then at the next execution of `run` (closing the short notification), `next_timeout` contains still the value of the short nofitication and is still smaller than the timeout for the middle notification. But dunst does not force to set a new timeout, as there is another existing timeout for the long notification.
Fixes #132
=> Fix notification timeouts

src/settings.c
Dunst currently just reads the normal config, when specifing a config file and this is not valid. Failing silently here, shouldn't be appropriate.
=> Fail when config file given via option not found

src/dbus.c
Distinguish between a failure to connect to DBus and a failure to
connect to the actual FDN DBus path.
This is possible, because `on_name_acquired` gets its DBus connection
passed as a parameter. If this parameter is NULL, there is no connection
established and the DBus name is not lost, because another notification
daemon is running.
Fixes #451
=> Distinguish DBus connection and name acquired error

src/dbus.c, src/dbus.h, src/menu.c, src/notification.c, src/queues.c
The `notification_closed` function is called even when a notification has
been pulled from history and re-emits the `NotificationClosed` signal,
this can confuse clients since it's not accounted for in the spec.
=> Don't emit NotificationClosed signal on redisplayed notifications

src/dbus.c, src/dunst.c, src/dunst.h, src/markup.c, src/markup.h, src/menu.c, src/notification.c, src/notification.h, src/queues.c, src/queues.h, src/rules.c, src/x11/x.c, src/x11/x.h, test/markup.c
Refactors `notification_init` to split it into multiple methods.
=> Refactor notification init

.travis.yml, .valgrind.suppressions, Makefile, src/utils.c
So, while we're already starting to improve our testsuite, I'd like to throw this one in, too.
It checks for definite leaks now in our testsuite, and more important, it'll fail if any leaks are found.
For this, we have to ignore that small xdg basedir leak and then tell valgrind to exit with an error code, when a definite leak shows up.
=> Add valgrind to travis configuration and check for leaks

src/dunst.c, src/dunst.h
This enforces to call wake_up in other files and not run(NULL).
=> Make run static to not export it

config.mk, src/x11/screen.c, src/x11/x.c, src/x11/x.h
Removes the neccessity of gdk3.
From #334:
> As it is right now it runs in ~20-30 microseconds and according to my tests when converting it to a png and back goes up to ~200-250 microseconds.
> 
> While that's obviously going to vary from CPU to CPU but a 10x overhead is a significant slowdown and I further discovered that this function gets called every time there's a focus change, that's a lot of needless CPU time.
That's correct. It's unacceptable to have a 10x slowdown. Additionally I think also it is bad spending on every focus change cpu power for the exact same calculation, when it's ok to save it in memory. So why should we spend even 20-30 usec on it?
With this PR, dunst generates the `cairo_surface_t` for the icon now in `notification_init` and saves it as a part of the …
=> Drop gtk and use gdk-pixbuf

Makefile, README.md, config.mk
Setting PREFIX to a location different to /usr, the install routine
fails to install the systemd and dbus service files. These are
installed, but in the PREFIX directory and not /usr. DBus and systemd
usually only read their files from /usr/ and ignore files in /usr/local.
Now by default, we're asking pkg-config, where to install it. Mostly,
this will be /usr and this conflicts the FHS. But it's the user's intent
to install dunst and (possibly) override the package manager's files
belonging to dunst.
At the current point, even DBus ignores the PREFIX and installs its
systemd service file to the location specified by pkg-config.
=> Add configurable path variables for services

CHANGELOG.md, Makefile, README.md, RELEASE_NOTES
As all remaining issues on the `1.3` milestone get closed via their associated PR, I started here to write the changelog and release notes for it.
=> Prepare release v1.3

src/notification.c
The progress hint is mostly used for progress bars but as discussed in
#437 there are cases where values > 100 make sense.
Fixes #437
=> Raise the maximum value of the progress hint

src/menu.c
The execvp function usually doesn't return and exits by itself. But,
when having an error, it returns. As a faulty browser setting could
trigger this, dunst has to handle this, as the forked child wants to
access the X11 server too, resulting in XIO errors.
Fixes #476
=> Handle execvp error in open_browser

Makefile
Git submodules have the property to have .git symlinked into the main
.git folder. On a symlink, the traling dot of a wildcard doesn't work.
Verify it via:
```
git init testrepo
cd testrepo
git submodule add https://github.com/dunst-project/dunst dunst
cd dunst
make
./dunst -v
git pull https://github.com/bebehei/dunst submodules
make clean
make
./dunst -v
```
Fixes the `-non-git` version number from @febs.
=> Build dunst also as a git submodule

Makefile, config.mk
Allows distros to specify a different path for the PKG_CONFIG binary, this mostly helps Exherbo that demands that tools like pkg-config be prefixed with the arch they are used for ( like x86_64-pc-linux-gnu-pkg-config i686-pc-linux-gnu-pkg-config )
=> add PKG_CONFIG make variable

Makefile
Before this commit, when building dunst in parallel, org.knopwob.dunst.service might get installed as an empty file. See https://bugs.debian.org/888760
=> Makefile: correct dependencies to fix race condition

.gitignore, .travis.yml, HACKING.md, Makefile, docs/internal/Doxyfile, src/dbus.h, src/log.c, src/log.h, src/notification.h, src/queues.c, src/queues.h, src/x11/screen.c, src/x11/screen.h, src/x11/x.c
This is a start to have the documentation with doxygen, which also contains markup to be able to compile it at the end of the day.
With this, one's able to compile a document to get an overview of the internal structures of dunst.
I've moved my own comments of the `queues.c` and `log.c` files to be compliant.
=> Parsable markup documentation with doxygen

CHANGELOG.md, docs/dunst.pod, dunstrc, src/dunst.c, src/notification.c, src/notification.h, src/option_parser.c, src/option_parser.h, src/queues.c, src/queues.h, src/rules.c, src/rules.h, src/settings.c, src/x11/screen.c, src/x11/screen.h, src/x11/x.c
Implements a rule to hide specific notifications on fullscreen
Fixes #142
=> Implement hiding on fullscreen

docs/dunst.pod, dunstrc, src/dbus.c, src/rules.c, src/rules.h, src/settings.c
make it possible to change frame color on section basis. For example when I receive notifications from [twitch.tv](https://twitch.tv/) I want them to be in twitch color scheme.
=> per section 'frame_color' parameter

.travis.yml, config.mk
Various changes to the travis and coveralls build process. More info about each change is in each commits body.
The X11LIB commit might seem out of scope but it is actually required for the next commit as if CFLAGS were moved it can cause an error since there's an empty `-L` parameter in the command.
=> Coveralls & travis build fixes

Makefile, config.mk
Fix a bug introduced in 678ea70 where since the CFLAGS variable was
simply expanded it ignored the VERSION variable which was initialized
later.
Unfortunately there is no way to prepend a value to a recursively
expanded variable so instead we have to split the hardcoded compiler
flags into separate variables and combine them all later in the
makefile.
Fixes #500
=> Do not expand config.mk variables on assignment

src/dunst.c, src/notification.c, src/queues.c, src/utils.c, src/utils.h
On Linux, CLOCK_MONOTONIC has got a bug. It does not count
onwards during sleep, albeit required by POSIX. This behavior
is reasoned with the requirement for poll().
Also the GLib people are sticking to this behavior in their
g_get_monotonic_time() function.
So we have to use a drop in replacement, which respects CLOCK_BOOTTIME
on Linux, as this is the clock, what would be CLOCK_MONOTONIC on POSIX
systems.
Fixes #492
=> Count monotonic time with Linux specific clocks

src/notification.c
According to the notification spec, only the body shall contain markup.
Therefore HTML symbols should get escaped in the summary, too.
Fixes #497
=> Escape the summary

config.h, config.mk, docs/dunst.pod, dunstrc, src/draw.c, src/settings.c, src/settings.h, src/x11/x.c, src/x11/x.h
As requested in issue [#358](https://github.com/dunst-project/dunst/issues/358) here's the support for round corners via the x11 shape extension.
=> Added: support for round corners

src/x11/x.c
From https://github.com/dunst-project/dunst/pull/420#issuecomment-343612682 in the review:
> With this PR, dunst is damn slow [...]
At this point, I couldn't pin down the problem to my hardware/setup or to the dunst PR. But now, as `xrestop` showed, we didn't free the `GC`s, which made the X process sluggish.
---
Relevant discussion: https://github.com/dunst-project/dunst/commit/a0f21f5c266b76b46f3b994b4ef6a0ca2909c475#commitcomment-29257834
=> Fix X11 memoryleak for round corners

src/icon.c, src/icon.h, test/icon.c
This PR implements tilde support for `icon_path` and absolute icon paths.
Albeit `icon.c` checked the icon, if started with a `~`, the check never had any effect :joy: 
Fixes #520
=> Implement paths for icons

config.h, docs/dunst.pod, dunstrc, src/settings.c, src/settings.h, src/x11/x.c
--- 
*Edit (@bebehei): Fixes #246*
=> Add options to specify mouse event

contrib/dunst_xr_theme_changer.sh
Hello. 
I've been reading some discussions about allowing Command Substitution `$(...)` and X resources access from the configuration file (#357).
Then, I headed to the dunst channel in freenode and `nikos` came up with the idea of creating a script to solve this problem.
So I created a wrapper to change colors and some other attributes according to the Xresources theme. Any tips or improvements?
=> Added dunst xresources theme wrapper

docs/dunst.pod, src/queues.c
This pull request adds a toggle command to the existing pause and resume commands. Dunst can now be toggled by sending a notification with a summary of "DUNST_COMMAND_TOGGLE".
=> Add a toggle command

src/rules.c
While the rule's field will get checked for a NULL value, the
notification's field won't get, as it's assumed to be non-NULL.
This is problematic, as there can be some corner cases, where the
notification's field is actually NULL.
Fixes #536
=> Avoid NULL values in fnmatch's parameters

src/queues.c
For notifications without any timeout, ttl can't be positive.
So when, show_age_threshold is active, dunst won't wake up, if there
are only notifications displayed without any timeout.
=> Wakeup also for infinite notifs when set show_age_threshold

src/dunst.c
Before this commit when using Dunst with multiple displays and
follow mode mouse/keyboard on a new notification (when no other
notifications are shown) a black window flickers up at the screen where
the last notification was shown.
By calling draw() before x_window_show the new window position will be
calculated and the window will be moved there before the window is shown
and thus remove the flickering.
=> draw the window before showing it

CHANGELOG.md, src/draw.c, src/notification.c, src/notification.h, src/queues.c, src/queues.h, src/x11/x.c
Let important notifications seep into displayed even if the `display` queue is full.
By checking the joint of both queues, if you concatenate now the `waiting` and `display` queues, the concatenated queue is still sorted. A push to waiting and `queues_update()` should show the important notifications even if there if display is full.
Previously, this would have required a timeout of a notification in the displayed queue. Now it works immediately.
Fixes #431 
Fixes #467
=> Concatenated queues

.github/ISSUE_TEMPLATE.md, .travis.yml, .valgrind.suppressions, CHANGELOG.md, Makefile, README.md, config.mk, src/dbus.c, src/draw.c, src/icon.c, src/log.c, src/notification.c, src/option_parser.c, src/queues.c, src/settings.c, src/utils.c, src/utils.h, src/x11/screen.c, src/x11/x.c
Just some miscellaneous changes, accumulated over the past weeks.
TBH, the libxdg removal came out of the blue. I found out today about the [`g_get_user_config_dir` function](https://developer.gnome.org/glib/stable/glib-Miscellaneous-Utility-Functions.html#g-get-user-config-dir), which makes `libxdg-basedir` irrelevant.
=> Misc patches

docs/dunst.pod, dunstrc, src/dbus.c, src/notification.c, src/notification.h, src/queues.c, src/rules.c, src/rules.h, src/settings.c
I took a shot at implementing a trivial "x-canonical-private-synchronous" ( #159 ).
I implemented it as simple string equivalent to a "--replace-id". I'm not
sure if there should be more to it (according to the [canonical spec](https://wiki.ubuntu.com/NotifyOSD) ?).
I did not handle ~~`x-canonical-`~~ [`private-synchronous`](https://github.com/dunst-project/dunst/issues/159#issuecomment-327675997) because I didn't want to add more non-standardized hints than necessary.
I couldn't wait for an official implem, just happy to share my take on it.
=> Implement x-canonical-private-synchronous hint

src/dunst.c, src/dunst.h, src/log.c, src/notification.c, src/queues.c, src/queues.h, test/dunst.c, test/queues.c, test/queues.h, test/test.c
=> Queues tests

.valgrind.suppressions, Makefile, test/greatest.h, test/log.c, test/notification.c, test/option_parser.c, test/test.c
- Add new tests for some low hanging fruits.
- update `greatest.h`
- skip the `_get_double` tests, if `atof`'s output doesn't match the output of its literal. This is mostly due to running valgrind (which can't handle extended precision) while using it on a system, with a libc, which is using extended precision.
=> Misc Testsuite updates

config.mk
libdbus was originally dropped with
820cfe73158b875ff6c0a00d646c7952c4cdb623 but it was never removed from
the dependency list.
=> Drop libdbus dependency

test/notification.c
Memory will only get freed, if the whole test method is gone through. In case of failure, memory leaks aren't important. But it's crucial not to fail with a segfault just for an assertion.
=> Improve notification tests

test/test.c
The log messages are useless during general and automated testing. But while developing tests, the warning messages might be an easy debugging option to check why one's own test currently fails.
=> Control to print log messages during test

src/dbus.c, src/draw.c, src/icon.c, src/icon.h, src/notification.c, src/notification.h, src/rules.c, src/utils.h, test/dbus.c, test/notification.c, test/queues.c
=> Checksummed icons

src/dbus.c
I'm not sure whether this case can happen in the wild, but if
artifically exercising the condition, I noticed it behaves
poorly. Specifically:
* The error_name parameter must be a valid D-Bus error name. It seems
conventional to set this to "org.freedesktop.Notifications.Error".
Without this change, the following error is thrown:
CRITICAL: g_dbus_method_invocation_return_dbus_error: assertion 'error_name != NULL && g_dbus_is_name (error_name)' failed
* Previously execution would continue even though the notification did
not decode, causing essentially a null pointer exception later.
Adds a return for this case.
* With those two things fixed, this case seems relatively silent -
"notify-send" invocations succeed even if the condition for the if
is "true". So, I added a warning log to …
=> Fix handling of case where notification decode failure occurs

docs/dunst.pod
My usecase is that I don't want to get notified for every new song
that plays (it's distracting), but I do want to bring them up via the
notification history.
=> Add a tip to the docs about how to skip initial display

.gitignore, Makefile
We currently do not keep track of header files in our Makefile so if one
is changed it can lead to multiple incompatible binary files being
linked. Instead we now create dependency lists for each source file and
recompile them if the need arises.
Fixes #594
=> Fix makefile not recompiling on header change

config.mk
Variables with trailing comments include the spaces leading up to the
comment (https://www.gnu.org/software/make/manual/make.html#Flavors)
so the corresponding install command looked like
"install -Dm644 docs/dunst.1 $(DESTDIR)/usr/share/man /man1/dunst.1"
=> Remove trailing spaces from MANPREFIX path

CHANGELOG.md, config.h, docs/dunst.pod, dunstrc, src/dbus.c, src/notification.h, src/queues.c, src/rules.c, src/rules.h, src/settings.c, test/queues.c
The hack described in https://github.com/dunst-project/dunst/pull/588 - setting `timeout = "1ms"` in a rule to skip display - doesn't always work.  Sometimes I see the notification for a brief flash.
There could potentially be a different workaround for this, say, skipping enqueue to the waiting list if the timeout is sufficiently low.
I've gone ahead and implemented an explicit option.  This will also make things work better in the case that `sticky_history` is set to `false`.  It also means that if `DUNST_COMMAND_PAUSE` has been used, when it gets unpaused it won't need to work its way through a queue of waiting notifications with tiny timeout.
=> Skip display rule option

src/settings.c
This is a proposed fix for #540.
I'm not reallty sure/happy with this fix but it seems to be the easiest.
I'm not sure wether we should overwrite `max_icon_size` if it's not 0, or should we assume the user knows what he's doing?
=> limit icon size when we have a fixed width

src/draw.c, src/x11/screen.c, src/x11/screen.h, src/x11/x.c
Changes DPI values online when receiving a corresponding XEvent.
To verify:
```shell
xrandr --dpi "${DPI}"
```
See the `Query the X11 screen's DPI instead of monitor` commit's description for further info.
Fixes #382
=> XRandR DPI Online Changes

src/menu.c
`\b` word boundary syntax doesn't work on FreeBSD which uses `[[:<:]]`, and `[[:<:]]` doesn't seem to be supported by glibc. Make extract_urls regex more portable by using `\<` for word boundary which is supported by both Linux (tested on Arch) and FreeBSD [1] (and probably by OpenBSD too [2], untested)
[1] https://www.freebsd.org/cgi/man.cgi?query=re_format&sektion=7&n=1
[2] https://man.openbsd.org/re_format.7
=> Make extract_urls regex more portable

src/dbus.c, test/dbus.c
=> Don't overflow when passing INT_MAX on DBus wire

src/option_parser.c
Sometimes these parse functions can have other side-effects such as the
sepcolor one which defaults to a custom color string if the value is
unknown. If the string is empty all of these functions should fail to
allow for the default to be used.
See #649 for details
=> option_parser: Fail early when parsing empty string

.valgrind.suppressions, config.h, docs/dunst.pod, dunstrc, src/icon.c, src/icon.h, src/notification.c, src/settings.c, src/settings.h, test/dbus.c, test/helpers.c, test/helpers.h, test/icon.c, test/notification.c
New attempt at #392, with [great ideas from @tsipinakis](https://github.com/dunst-project/dunst/issues/392#issuecomment-558519183) taken into account. Have still not attempted to test/take into account any DPI-related functionality, so cannot say yet how/if it will affect the outcome. 
Do you want more tests for the scaling functionality? Current tests pass.
Implementation details: I moved the scaling responsibility to the lowest functions in the call hierarchy involved in loading the images - both when loading from disk and from the notification message so responsibilities are clearer code-wise. Made some functions static that are no longer needed elsewhere.
=> Implement #392, take 2

config.h, docs/dunst.pod, dunstrc, src/draw.c, src/option_parser.c, src/option_parser.h, src/settings.c, src/settings.h
This adds the option `content_alignment`, which allows the user to set the vertical alignment of the notification's content (i.e. icon and
text) to either:
- top (`CONTENT_TOP`),
- center (`CONTENT_CENTER`, default), or
- bottom (`CONTENT_BOT`).
The default preserves current behaviour, while the other options fulfill #486.
I am open to any suggestions or comments regarding naming and/or code-style.
=> Adding vertical content alignment control.

src/utils.c, src/utils.h
For weird reasons, the `HOME`-variable might not always be set. So we
should fallback on something more reliable.
Fixes #693
=> Retrieve user's home from passwd entry as fallback

config.mk
As it turns out, not every distribution link (lib)notify by default, so I didnt catch that earlier. I separate install and install-dunstify again because autoconf checks if string "dunstify" is applied as a make argument and then add libnotify to pkg_config_pack.
It would be awesome if someone could update the wiki page on this topic.
I am kinda new to C "building"/autoconf so I didnt fully understand respectively underestimated my change, sorry for that.
=> Fix dunstify installation

src/x11/screen.c
In dwm and similar window managers, it's common to often have empty
tags, and navigate to them with the intent to create clients there. If I
navigate to one of those empty tags with a dunst notification visible
and follow=keyboard set, the notification warps over to the default
screen.  If I then open a client, it then warps back, which is pretty
jarring.
This is mostly an artefact of the implementation of follow=keyboard --
if we fail to get a focused window, we use the default screen. However
this case isn't necessarily really a "failure" on window managers like
dwm where it's a common occurrence to end up with no clients on the
screen, whereas that would be significantly rarer on (say) GNOME or KDE.
A guess that's more likely to fit user expectations is falling back to
where the mouse …
=> follow=keyboard: Fall back to follow=mouse instead of XDefaultScreen()

Makefile, docs/dunst.pod, docs/dunstctl.pod, dunstctl, src/dbus.c, src/dbus.h, src/dunst.c, test/dbus.c, test/dunst.c, test/test-install.sh
Work in progress, I expect to be finish & polish it during the next week.
=> Implement a command line control (dunstctl)

docs/dunst.pod, docs/dunstctl.pod, dunstctl, src/dbus.c
Implements the feature proposed in #709 to allow toggling the pause state via `dunstctl`.
This also fixes #710 to improve user intuition.
=> Allow toggling pause state via dunstctl

dunstrc
Current PR enables by default the notification icons.
On a default installation of dunst these icons are disabled until the user explicitly overrides this setting in their corresponding `dunstrc`.
=> Change default for icon_position in dunstrc

src/draw.c, src/draw.h, src/x11/x.c
1. Original shaping mask caused antialiasing pixels to be cut, leading to ugly look. Solved by increasing mask corder radus by half-borderwidth, but not less than 1pix (for zero-width border).
2. And when border width is set to zero, it should not be painted. Current approach caused transparent pixels from AA to sum, producing subtle edge-like artifact at corners.
=> Fix ugly frame

src/draw.c, src/x11/x.h
Besides core rgba support I tried to implement support for arbitrary hex color string length (though limited by maximum unsigned length for given machine), as well as rgba() and rgb() formats, using scanf.
What's also interesting, adjacent non-overlaping areas are better to be combined in additive mode, so that fading out pixels at bounds mix correctly. I'm not sure though, if cairo uses alpha channel correctly (must be summed too, not like how it does with multiply op), but at least it removes artifacts between frame and background, visible when both are equally contrast with background.
Btw, imho colors are better to be parsed once on theme loading instead of on each draw().
=> Rgba support

config.h, docs/dunst.pod, dunstrc, src/dbus.c, src/queues.c, src/queues.h, src/settings.c, src/settings.h, test/queues.c
closes #731
However I was not able to test it because of X BadAtom error:
```
./dunst -print -verbosity debug
{
appname: 'dunst'
summary: 'startup'
body: 'dunst is up and running'
icon: 'dialog-information'
raw_icon set: false
icon_id: 'dialog-information'
desktop_entry: ''
category: 
timeout: 10000
urgency: LOW
transient: 0
formatted: '<b>startup</b>
dunst is up and running'
fg: #888888
bg: #222222
frame: #aaaaaa
fullscreen: pushback
progress: -1
stack_tag: 
id: 2
actions: {}
script: (null)
}
DEBUG: RUN
DEBUG: XEvent: Ignoring '65'
DEBUG: XEvent: processing 'CreateNotify'
DEBUG: XEvent: Checking for active screen changes
DEBUG: XEvent: Checking for active screen changes
DEBUG: XEvent: Checking for active screen changes
DEBUG: XEvent: Checking for active screen changes
DEBUG: XEvent: …
```
=> Add ignore_dbusclose settings

src/draw.c
Check all possible causes of division by zero in the calculation of the radius.
This fixes #746, and correctly checks for division by zero.
Checking `s == 0` too might be a bit overkill though.
=> Fix possible division by zero in radius calculation.

src/dbus.c
=> Emit signal when `paused` property changes

dunstrc
The [shortcuts section is deprecated](https://dunst-project.org/documentation/#Shortcut-section-DEPRECATED-SEE-DUNSTCTL) in favor of dunstctl. Having it in the example dunstrc is confusing to new users, at least it was to me.
=> Remove deprecated shortcuts section

src/settings.c
In my opinion this is a saner default.
=> Turn icons on by default

config.h, docs/dunst.pod, dunstrc, src/draw.c, src/notification.c, src/notification.h, src/rules.c, src/rules.h, src/settings.c, src/settings.h, test/functional-tests/dunstrc.progress_bar, test/functional-tests/test.sh
This PR addresses #772. It add a progress bar at the bottom of the notification when a value is passed via a dbus hint. Settings have been added to turn off the progress bar.  The old behaviour of showing a percentage in text can still be used the same way and even in conjunction with the progress bar.
A highlight colour is added and used for drawing the progress bar.
_This is what it currently looks like_
Example usage
``` bash
notify-send -h int:value:10 "Brightness" 
```
=> Add progress bar

test/functional-tests/dunstrc.nomarkup, test/functional-tests/test.sh
When testing, I noticed some warnings, so I fixed them.
Also, the no markup configuration had markup in the config.I deleted that, because that made it harder to check if markup was added.
=> Fix some tests

docs/dunst.pod, src/draw.c, src/draw.h, src/dunst.c, src/output.c, src/output.h, src/queues.c, src/x11/screen.c, src/x11/screen.h, src/x11/x.c, src/x11/x.h
This commit adds an output struct which abstracts the X11 specific
functions and makes it possible to easily create a drop-in wayland
output.
It also fixes a bug in wayland where notifications won't disappear.
This is because wayland doesn't give access to user input when a
client is not in focus. This way it seems like the user is always
idle. The idle functionality is now disabled in Wayland until proper
support is added.
Dunst should now work fine on wayland using X11 compatibility.
Only the idle functionality won't work, obviously.
=> Create abstract output and fix wayland bug

docs/dunstctl.pod, dunstctl, src/dbus.c
This will add the dbus properties
* `displayed`
* `waiting`
* `history`
and extends `dunstctl` with the sub-command `status`, which provides this information.
Currently I'm not sure, if `history` is the right term. Maybe `shown` fits here better.
See also the feature request #792.
=> Get the number of notifications

Makefile, test/greenest.awk
Colorizing the test output really helps with finding what test failed. This adds a dependency on awk for testing. It might be possible to implement this more cleanly/robustly.
Closes #812
=> Colorize test output.

Makefile, config.mk, docs/dunst.pod, src/settings.c, test/test-install.sh
Fixes #795 
The makefile still isn't fully xdg compliant. If the user has set `$XDG_CONFIG_DIRS` it should be reflected our install, I believe.
I didn't know the best way to implement that, but [this](https://www.gnu.org/software/make/manual/make.html#Directory-Variables) is some make documentation about all the standard directories, and [this](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html) is the spec.
=> Change config location to /etc/dunst/dunstrc

docs/dunst.5.pod, src/icon.c, src/icon.h, src/notification.c, src/notification.h, src/utils.c, src/utils.h, test/icon.c
Addresses #767  and  #653. This PR sets environment variables for scripts to use. Let me know if I have to add more or if the naming should be changed. I still need to do the documentation, but I wanted to get some comments before that.
=> Set environment variables for scripts

src/notification.c, src/queues.c
These commands may be used for a DoS attack. Specifically, an
application that's running from a sandbox (e.g.  websites with
notification permission) can toggle the permissions.
This is a low severity issue but since dunstctl is available which
performs the exact same task there is no reason to leave this in.
Credit to Vít Šesták for reporting this.
=> Drop support for DUNST_COMMAND_*

src/draw.c, src/output.c, src/output.h, src/wayland/wl.c, src/wayland/wl.h, src/x11/x.c, src/x11/x.h
=> Wayland: fallback to X11 output when initialization fails

src/dbus.c, test/dbus.c
Dunst supports displaying the first frame of an icon, thus it seems reasonable that it should announce that capability with `icon-static`.
`"icon-static" | Supports display of exactly 1 frame of any given image array. This value is mutually exclusive with "icon-multi", it is a protocol error for the server to specify both.` 
from https://developer.gnome.org/notification-spec/#hints
I check for this capability in another project. notify-osd is the only other I know that supports/announces it, however dunst doesn't when it could since it has this already. I've been relying upon the `image-path` hint as an alternative which is more or less a fire and forget approach but it'd be nice to know if the capability exists
=> Add icon-static server capability

src/log.c
It's useful to see what crashed your program when testing. Unfortunately
there's no way to distinguish the DIE way of logging from critical
logging.
This commit also fixes a bug where loglevel error wouldn't function,
because the message level also contains other flags.
=> logging: Set loglevel to error when testing.

src/draw.c, src/draw.h, src/dunst.c, src/icon.c, src/icon.h, src/notification.c, src/output.c, src/output.h, src/wayland/wl.c, src/wayland/wl.h, src/x11/x.c, src/x11/x.h, test/icon.c
Fixes #836
@bebehei This PR currently only implements scale detection on wayland. I'm making this PR already so you know I'm working on it.
To test it on sway, it's really easy:
`swaymsg output "*" scale 1.5`
Sway will message a scale of 2 to dunst and it will scale it down to 1.5 afterwards.
=> wayland hidpi support

docs/dunst.5.pod, src/dbus.c
=> Add dbus hightlight hint

src/icon.h, src/queues.h
`make doc-doxygen` did not run, because some parameters were not named correctly
=> fixed doxygen generation

Makefile, README.md, config.mk
This PR proposes better default locations, so locally installed dunst versions can coexist with distro version, as it should be. This fixes #907.
=> Better default installation locations for systemd and dbus units

Makefile, config.mk, src/settings.c, test/test-install.sh
This PR proposes a fix for several issues with dunstrc. For starters, it was installing to the wrong location ('/etc/dunst/dunstrc') instead of at least ('/etc/xdg/dunst/dunstrc'), which would be the right place, were it not a distro managed confdir. On top of that 'make install' would happily overwrite whatever file is there already, violating at least the Debian Policy of never silently overwriting user/admin configs. Locally installed software is expected to put its system-wide conffiles in '/usr/local/etc'. In this case the XDG_CONF_DIRS spec (XDG base directory spec) comes into play, so the right location is '/usr/local/etc/xdg/dunst/dunstrc'. With theses changes, installation of 'dunstrc' is made to that path.
Plus, now install won't overwrite an already existing dunstrc, i.e. on …
=> Dunstrc: Actually use it and be less disruptive on (un)install

src/settings_data.h
These have been accidentally removed with the setting refactor
Fixes #916
=> settings_data: Add in mouse context options again

src/utils.c, test/markup.c, test/utils.c
Some notifications might include markup (XML) symbols without escaping
them correctly. Instead of cutting off the notification text from that
symbol, ignore those symbols and escape them instead.
This isn't a full workaround, since it still strips all the markup, even
from the title. But since this is user error anyways, it is good enough.
Fixes #900
=> markup: Strip only symbols which include a closing delimiter

README.md
This should help users that did not expect the removal of some features
discover alternatives. See https://github.com/dunst-project/dunst/issues/940 for example.
=> docs: add a troubleshooting section

src/draw.c, src/x11/x.c
This may solve issue with incorrect window sizes.
It also fixes mouse position calculations. So the correct notification will be closed again when clicking on it.
Fixes: #950 #966
=> x11: fixes for dpi scaling

dunstctl, src/dbus.c, src/rules.c, src/rules.h, src/settings_data.h
This feature allows to enable or disable rules through dunstctl whenever you please.
Its main use case for me is muting certain notifications for a period of time, or changing the color of notifications depending on which "mode" I want. Instead of changing the configuration and reloading dunst (which is tedious), with this feature I can easily script it and apply it to new notifications.
In configuration:
```
[red]
background = "#ff0000"
summary = "*"
enable = false
```
Then you might enable it whenever you want with
```
dunstctl rule red enable
```
Or disable it when you're tired
```
dunstctl rule red disable
```
Rules are enabled by default unless you explicitly disable them.
I created it for myself, but maybe someone else can take advantage of it, so I'm sharing the code. Its a simple …
=> Feature: Enable or disable rules on the fly

contrib/notification-history.sh, dunstctl, src/dbus.c, src/queues.c, src/queues.h, test/queues.c
The current implementation tries to retrieve notifications stored in the
history buffer (which means they've been either discarded or hidden by
the user) and does so using the existing D-Bus system. However the
output of the dbus-send command is (in my opinion) super ugly and
unusable for any practical scripting application.
This is VERY much still a work in progress.
Any additional suggestions or ideas are welcome.
=> dbus/dunstctl: add history command (#307)

docs/dunst.5.pod, dunstrc, src/notification.c, src/notification.h, src/rules.c, src/rules.h, src/settings_data.h
The `icon` setting will be replaced by `default_icon`, so it will be removed in a future version. But for now it works again.
=> Fix icon setting and add default_icon settting

docs/dunst.5.pod, src/draw.c, src/wayland/wl.c, src/wayland/wl_output.h
This fixes the notification bleeding into other screens as discussed in #951.
This fixes the main issue described in ticket for X11.
This code will work for Wayland eventually once `get_active_screen` is implemented correctly in `wl.c`.
For now we increase the stub resolution to a value which does not get exceeded with "common" screen resolutions.
Thanks an best regards
=> Clamp maximum notification width to screen width

src/draw.c
Hey again,
noticed today that my notifications looked all wonky with a huge icon on the right side.
Turns out that with 0b1cf92960df3f39bb732056c37af03e6c676df6 the `icon_position` was not being evaluated correctly.
The check for `icon_position = off` was patched out with no replacement (`settings.icon_position != ICON_OFF && n->icon`).
This commit fixes this by reapplying the needed checks.
Maybe the tests in https://github.com/dunst-project/dunst/blob/master/test/notification.c need some adjustment for `ICON_OFF` to catch issues with this next time.
Best regards,
Michael
=> Fix 'icon_position = off' not being respected

docs/dunst.5.pod
It was last changed in https://github.com/dunst-project/dunst/commit/a7b65b2e7b4919039d687232c3cd10f533c256b0 but the documentation was never updated.
=> Fix default `format` value in documentation

src/dbus.c, src/icon.c, src/icon.h, src/notification.c
This PR fixes two cases where the resulting icon size would not be the same as `icon_size`.
=> Always scale icons to `icon_size`

docs/dunst.5.pod, src/rules.c, src/settings.h, src/settings_data.h, test/rules.c
This enables more advanced regular expression syntax. It can be enabled with `enable_posix_regex`.
See the man page for more information.
Fixes: #1013
Fixes: #645
Fixes: #658
Related: #659
=> rules: implement regex matching

docs/dunst.5.pod, src/option_parser.c
Not sure if you want that feature in dunst or not, but this PR fixes regression introduced in 1a456a56 which made it impossible to use negative offsets (issue #1026). I personally think it's useful. Tested on X11 only. I don't have Wayland around, sorry.
fixes #1026
=> Allow negative offsets (fixes issue #1026)

src/utils.c
Found this while preparing update for Fedora - as we have `XDG_DATA_DIRS` set in the systemd environment, dunst wasn't reading the system-wide config.
Fixes #1041
=> Use correct variable for the configuration file paths

src/draw.c
Currently the notification size changes according to the "scale" option, but the offset does not. I believe it makes more sense to scale them together
=> Scale offset according to DPI

dunstctl
Removes `-l` option from the `busctl` invocation since it's only relevant to the `list` outputs.
That fixes the command to fail on invocation with an internal error
```
busctl: invalid option -- 'l'
```
See [buctl(1)](https://www.freedesktop.org/software/systemd/man/busctl.html)
=> Fixes dunstctl history command

src/wayland/wl.c
=> Mako wayland fixes

src/x11/screen.c
Commit e8fc45da6371 ("follow=keyboard: Fall back to follow=mouse instead
of XDefaultScreen()", PR#708) introduced the behaviour that we fall
back to follow=mouse if there is no focused client in order to
accommodate for window managers where sitting on the root window is
normalised, like dwm.
Commmit ebcd20d8d040 ("Fix process of gettign the active monitor",
PR#809) added support for multiple X screens on one display. However, it
broke the functionality introduced in the previous PR, because
explicitly focusing the root window results in XGetInputFocus()
returning the root window, not PointerRoot.
Fix this by explicitly checking if the focused window is the root
window.
=> follow=keyboard: Fix regression where we don't fall back to mouse

contrib/notification-history.sh
My main intention is minimize calls to jq since (on my thinkpad) each takes 50-100 ms, which can add up to a noticeable delay (~400ms for each notification) until the window first appears.
Seeing past notifications is an important part of how I use notifications, so I polished the script.
=> notification-history.sh: Rewrite for speed

Makefile, README.md, config.mk
solves #1122 's libnotify, but not the libXScrnSaver problem
=> make libnotify & dunstify optional

src/dbus.c, src/dbus.h, src/draw.c, src/dunst.c, src/icon-lookup.c, src/notification.c, src/option_parser.c, src/queues.c, src/rules.c, src/settings.c, src/utils.c, src/wayland/foreign_toplevel.c, src/wayland/libgwater-wayland.c, src/wayland/wl.c, src/x11/screen.c, test/dbus.c, test/icon-lookup.c, test/input.c, test/option_parser.c, test/utils.c
Similarly to what @ammgws noted in #765, for `paused`, the various Length PropertiesChanged were not emitting PropertiesChanged when notifications were opened/closed. This change makes sure that these values are always kept up to date.
=> DBus PropertiesChanged signal not being emitted for *Length PropertiesChanged

docs/dunst.5.pod, dunstrc, src/draw.c, src/settings.h, src/settings_data.h
I added an option to set the icon image corner radius.
The variable name is `icon_corner_radius` and it would just have to be added to the `dunstrc` file.
It looks like this when used and it seems to work fine for me: 
Example:
=> Add option to set icon image corner radius

src/draw.c, src/wayland/wl.c
Please review carefully, I'm not familiar at all with dunst nor Wayland. This might not be the right way to fix #1147.
=> Fix #1147 by checking NULL pointers

.github/workflows/main.yml, src/icon-lookup.c, src/rules.c, test/icon-lookup.c
We need to use g_malloc since it handles the error conditions of malloc and terminates the program immediately. We do not have to check for error codes we could not handle anyways.
=> Enforce g_malloc over malloc in project

dunstify.c
It took very long time for me to figure out what is that "summary" dunstify says it needs.
```
$ dunstify
I need at least a summary
$ dunstify --help
Usage:
dunstify [OPTION…] - Dunstify
Help Options:
-?, --help                  Show help options
Application Options:
-a, --appname=NAME          Name of your application
-u, --urgency=URG           The urgency of this notification
-h, --hints=HINT            User specified hints
-A, --action=ACTION         Actions the user can invoke
-t, --timeout=TIMEOUT       The time in milliseconds until the notification expires
-i, --icon=ICON             An Icon that should be displayed with the notification
-I, --raw_icon=RAW_ICON     Path to the icon to be sent as raw image data
-c, --capabilities          Print the server capabilities and exit
-s, …
```
=> Change option description string

src/dunst.c
The show_age_threshold can be set to -1 to disable the feature that updates notifications with their age.
In this scenario the `queues_get_next_datachange` may return -1 to indicate that there is no next wakeup time (e.g. when there are permanent / critical notifications).
The code that calls `queues_get_next_datachange` should take this scenario into account and not schedule another timeout if -1 is returned.
Addresses #1163.
=> High CPU usage when show_age_threshold = -1

src/queues.c
Related to issue #1102. Tested hastily, seems to fix the high CPU load.
=> Get_next_datachange: use `start` to compute timeout

src/icon-lookup.c, src/ini.c, src/option_parser.c, src/rules.c, src/settings.c, src/utils.c
The purpose is to avoid any failure in realloc, leading to null pointer dereferences/memory leaks. Failure in g_realloc will also terminate Dunst.
@bebehei, waiting for any further suggestions/reviews. :)
=> Replace realloc with g_realloc in icon-lookup.c

docs/dunst.1.pod
A simple spelling fix in man page dunst(1).
=> Fix manual page typo

docs/dunst.5.pod
This is a quick fix for a grammatical error in the docs. In man pages 5 under the "Global section: follow" heading, change the sentence "When either of the is used..." to "When either of them is used..."
=> Changes "the" to "them" in man pages 5 under the "follow" heading

docs/dunst.5.pod
The `always_run_script` config option was mistyped as `always_run_scripts`.
=> docs: fix variable typo

contrib/dunst.fishcomp, contrib/dunstctl.fishcomp, contrib/dunstify.fishcomp
Add completion files for all commands for [fish-shell](https://github.com/fish-shell/fish-shell).
NB: I left out completion for the `rule` subcommand of `dunstctl` as there currently is no way of getting defined rules in a generic way (e.g. both the completions for bash and zsh try to parse the default config, which might not be the configuration being used and also ignores drop-in files altogether).
=> Add fish completions

contrib/_dunst.zshcomp, contrib/dunst.bashcomp, docs/dunst.1.pod, src/dunst.c, src/option_parser.c
The output of `dunst -h` differs from the one of `dunst --help` due to how the usage string is constructed. Furthermore, the options `-print` and `--startup_notification` are not listed at all (due to incorrect ordering of options).
This PR refactors `cmdline_find_option` to handle more than two alternatives (which fixes the first issue, when calls to `cmdline_get_*` are merged) and reorders command line parsing in a way, that all currently available options are listed.
NB: I've added `-startup_notification` as alternative to `--startup_notification` as it was the only option only available with to hyphens and thus breaking consistency.
=> Fix commandline handling

dunstctl
Fixes: 6d250b583485 ("add multiple pause levels")
Fixes: dbe836731127 ("Add history-clear command (#1131)")
Fixes: 82fb1d996ef0 ("remove d from pause level commands")
Fixes: 6d250b583485 ("add multiple pause levels")
=> dunstctl fixes for "Add multiple pause levels" (bashisms, whitespace, …)

docs/dunst.5.pod
I came across the typo while reading the man page and then the first four entries ending without periods and all others ending in a period seemed strange, so I changed that as well.
=> Fix a typo and add periods to end all hints consistently.

dunstctl
As noted in [this comment](https://github.com/dunst-project/dunst/pull/1212#discussion_r1389414771) usage of brackets is a bit inconsistent in the usage output of dunstctl.
Just optional argument should be put in `[]`. Required ones are without them.
=> Use brackets consistently in dunstctl usage

test/greatest.h, test/markup.c
The new version disallows nesting of tests. Therefore, `test_markup_strip_a` and `test_markup_strip_img` were converted to suites. This also means, that the number of tests is formally reduced by 2.
=> Update greatest to v1.5

.valgrind.suppressions, docs/dunst.5.pod, src/utils.c, test/option_parser.c, test/utils.c
This fixes #1173 - in combination with #1210
This is a spin-off of #1210 to properly handle environment variables for defining path like variables.
Open questions:
* Which flags to pass to `wordexp`?
* `0` (like e.g. i3wm does) - allows for a maximum of flexibility. E.g. the output of a script could be used to set the variable (`default_icon = $(some_random_command)`), but this also allows for arbitrary code execution.
* `WRDE_NOCMD` - prohibits expansion of commands, but allows for all variables - even undefined ones.
* `WRDE_NOCMD | WRDE_UNDEF` - strictest way of expansion, which ignores undefined variables
* Is `LOG_W` enough to inform user of failed expansion? Should this be more detailed wrt. kind of failure?
=> Use wordexp to resolve variables like $HOME in path like settings

src/draw.c, src/draw.h, src/x11/x.c, test/draw.c
I divided the patch in #1213 to simplify things a bit. This first part only deals with the rendering of the corners. The second part (which I will add soon) adds support for the customization option to change corner profile. Anyway, refer to #1213 for any information on the changes.
=> Corners patch part 1

test/icon-lookup.c, test/notification.c
This is a temporary fix to #1228 until we figure out what causes the issue in first place (icons not being loaded). 
This simply adds assertion so that if the icon is null the test suite will not segfault
The ci will fail...
=> Assert that notification icon is not null in tests

src/draw.c
This is a simple addition to text rendering that allows fallback fonts. This improved my experience with #1211 when using a monospace with font awesome glyphs.
However this is not a complete solution! The problem with multiple fonts is in pango design.
It allows only one font to be loaded when rendering. In this patch I simply add the pango attribute for font fallback.
=> Enable pango font fallback

src/dunst.c
Fixes #1196
All tests passing:
```
$ make test
[...]
Total: 189 tests (85447 ticks, 0.085 sec), 2430 assertions
Pass: 189, fail: 0, skip: 0.
```
=> Run(): clear previous timer id if needed

config.mk, src/icon-lookup.c, src/icon-lookup.h, src/option_parser.c, src/option_parser.h, src/output.c, src/rules.c, src/settings.c, src/wayland/foreign_toplevel.c, src/wayland/wl.c, test/draw.c, test/icon-lookup.c, test/option_parser.c, test/queues.c
As noted in #1229 the code does not compile cleanly on recent compilers.
* I increased the standard to use mainly to silence the clang warnings about `_Static_assert`.
* I'm not sure whether wayland allows for `NULL` in callbacks and couldn't find any information. So, I decided to just implement all needed handlers as empty methods to get rid of the `noop` functions.
* I rewrote all functions having warnings about dangling pointers to use a suite to set up a real test. This way, the message is `const` within the scope of the function and the warning is suppressed.
At the moment, this builds without warnings on GCC 13.2.1 and clang 16.0.6.
Fixes #1229
=> Fix compiler warnings

src/wayland/wl.c
The callback `output_handle_description` is just used when `WL_OUTPUT_NAME_SINCE_VERSION` is defined and so, this function should defined only then as well as it otherwise is flagged as being unused which breaks the build.
=> Fix compiler warning/error on master

.valgrind.suppressions, src/wayland/wl.c
This is related to the introduction of `wordexp` in e9a27c0 but did go unnoticed as it seems to be detected just by newer versions of valgrind (I would rule out musl here as the `wordexp` code was not touched in ages and `getdelim` was last mentioned in the 1.1.22 version while the old alpine image already shipped 1.1.24).
This isn't an issue with the current images but newer versions of alpine fail to complete without it (see [this comment](https://github.com/dunst-project/docker-images/pull/8#issuecomment-1948756512)).
=> Suppress alpine allocation issue

Makefile, README.md, config.mk, docs/dunst.5.pod, src/option_parser.c, src/output.c, src/output.h, src/settings.c, src/settings.h, src/x11/x.h
With these changes you can compile dunst with only wayland support.
Important note: At the moment I don't have a working wayland setup so I can't test if everything is ok. I guess so since the changes are minimal, but if someone with wayland could test this it would be great.
Update: Narrat reviewed the changes. Somewhere in the near future this will be merged hopefully
Closes #1008
=> Allow compilation without X11

src/wayland/wl.c
Adwaita, the default icon theme for many distributions, decided to stop providing legacy Xcursor icons in favor of the GTK/CSS names[1]. This requires us to probe for "default" instead of the "left_ptr", as the latter is no longer available in Adwaita.
Keep the fallback to "left_ptr" for more conservative themes.
[1]: https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/commit/74e9b79471236320d2af4925d6c5bb7df22380ce
=> Wayland: suport GTK/CSS cursor names

dunstctl
Previously showed "line 130: 3: unbound variable" instead of the pretty error message.
=> Fix `dunstctl rule` error when not providing rule state

src/x11/x.c
Despite what the XrmSetDatabase docs say, it may try to free the database, resulting in memory corruption. Prevent that by making sure it has no db to act on. If it's past the first run, we will have done XrmDestroyDatabase above anyway. This causes a segfault, reported in issue #1256.
From the XrmSetDatabase man page:
> The database previously associated with the display (if any) is not
> destroyed.
But this is patently false, from the source in Xlib's src/Xrm.c:
void XrmSetDatabase(
Display *display,
XrmDatabase database)
{
LockDisplay(display);
/* destroy database if set up implicitly by XGetDefault() */
if (display->db && (display->flags & XlibDisplayDfltRMDB)) {
XrmDestroyDatabase(display->db);
display->flags &= ~XlibDisplayDfltRMDB;
}
display->db = database;
UnlockDisplay(display); …
=> x11: Prevent memory corruption in XrmSetDatabase

src/dbus.c, test/dbus.c
... and while at it also fix all memory leaks from this method.
=> Add tests for NotificationListHistory

test/option_parser.c
The same as already done in fe5ac680af0a7c6831205b02360172dbdc06185b but plain buffers were re-introduced when the corners patch landed.
@bynect fyi
=> Get rid of new warning about dangling pointers

src/icon-lookup.c, src/icon.c
Remove extra newlines and move a string empty upwards
=> Fix logging in icon code

docs/dunstctl.pod
This fixes #1280 and also the comment mentioned in #1242.
While at it, I also did a small reformatting of the page.
=> Update dunstctl manpage

.github/workflows/main.yml, .valgrind.suppressions
Yet another try of getting the pipelines to work. This continues/replaces #1303.
Notable changes:
* update to use latest images from `dunst-project/docker-images`
* updated the images for Debian bookworm and Alpine (see the other repository) to add some more missing dependencies
* `make test-coverage` has issues running in parallel ⇒ `-j` should not be used
* don't kill matrix jobs when one fails in order to see which targets are really broken
* update actions where possible
* `misc-doxygen` doesn't need to be a matrix, if it is a `1x1` matrix
TODO:
=> Rewrite github action

src/dunst.c, src/queues.c, src/settings.c, src/settings.h
settings.print_notifications and settings.startup_notification were always set to zero by load_settings
=> Fix settings initialization

src/icon-lookup.c, src/icon.c, src/notification.c, src/queues.c, src/settings.c, src/utils.h
Should fix #1305 . I added the null check to the places where a null string could occur. I may have missed some.
=> Add printf null checks

.github/workflows/main.yml
v3 is facing some issues at the moment. v4 should be fine as coverage reports are generated on fedora which should have a recent Node.js version.
=> Update codecov-action to v4

src/dunst.c
This logic was over-complicated and caused multiple bugs. This hopefully remediates to this for good. Fixes #1196.
I finally took the time to look at the timer logic of the `run` function, check what was actually needed, and came up with this simplification. I tried to document it in the function, feedback welcome :)
This passes `make test` correctly:
```
$ make test
[…]
Total: 193 tests (84019 ticks, 0.084 sec), 2529 assertions
Pass: 193, fail: 0, skip: 0.
```
Issue #1196 is also fixed: I tried manually the scenarios I could think of (including the one mentioned in the issue) and could not get a `Source ID xx was not found` error.
Note for the future: replacing `g_timeout_add` with [`g_timeout_add_once`](https://docs.gtk.org/glib/func.timeout_add_once.html) would enhance robustness, in …
=> Main loop: rework timer logic

.github/workflows/main.yml
There should be a valid token now and thus the restriction for pull requests should not be needed anymore.
=> Re-enable coverage for all pushes

Makefile, test/test-install.sh
Completions in fish are just loaded if the file ends  with .fish.
=> Fix file suffix for fish completions during installation

README.md, completions/_dunstctl.zshcomp, completions/dunstctl.bashcomp, completions/dunstctl.fishcomp, docs/dunstctl.pod, dunstctl, src/dbus.c, src/settings_data.h, test/dbus.c
As noted in #1209 a completion for `dunstctl rule` is currently not feasible due to missing information about which rules exist. This PR proposes to add a new DBus method to list all configured rules and use this information for a proper completion.
NB: Completion for bash and zsh will be adjusted when this approach is considered okay. Also, I'd add more information about the rules in the response in this case.
=> Export rules via dbus

completions/dunst.bashcomp, completions/dunstctl.bashcomp
A completion was not selected even if the match was unique as `compgen -W` has to be used for this.
Also, fix enabling a rule which would've been completed to `enabled`, which is invalid.
=> Fix bash completion

docs/dunst.5.pod
Remove the message about shortcuts deprecation, as they were reintroduced to the configuration as part of the global section in commit 17822228
=> Update config man page

Makefile, test/test.c
=> test: use argument as test data directory

docs/dunst.5.pod
Fix the broken link in the `man 5 dunst` page (link to the page describing categories in freedesktop's notification specs)
https://specifications.freedesktop.org/notification-spec/latest/ar01s06.html gives a 404 error.
https://specifications.freedesktop.org/notification-spec/latest/categories.html seems to be the correct link
=> Fix broken link to freedesktop's notification specs in man page

dunstctl
That way the user can more easily use this in a script
instead of
```bash
if [[ "$(dunstctl is-paused)" == "true" ]]; then
{...}
fi
```
they can do
```bash
if dunstctl is-paused -e; then
{...}
fi
```
=> feat: exit with `1` when paused for `is-paused`

src/menu.c, test/functional-tests/dunstrc.default, test/functional-tests/test.sh
=> Reverse order of context menu

README.md, dunstctl, src/dbus.c
=> Check DBUS_SESSION_BUS_ADDRESS and give more meaningful errors

dunst.systemd.service.in
By default, systemd would place it in `app.slice` which doesn't make sense; that's where apps go, not daemons that are part of the desktop session.
`session.slice` makes a lot more sense for a daemon that's part of the desktop session.
Related: https://github.com/flatpak/xdg-desktop-portal-gtk/pull/504
=> Place dunst.service in session.slice

src/option_parser.c, src/utils.c, src/utils.h
As solicited by @stapelberg in the discussions this will be a (temporary) solution for backward compatibility of `height`.
This will *not* make it into v2, but for now is fine.
I will need to release a 1.12.1 anyway due to the graphical bug #1406
=> Add backward compatibility for height + notice

completions/_dunstctl.zshcomp
Simple, just added history-clear to the zsh completion.
=> feat(completions): Added history-clear completion for zsh

src/dbus.c
Thought it may be prudent of me to offer a fix once it occurred to me the fix would probably take less work than the workaround...
Adds the following to `dunstctl history` JSON output:
- urgency
- stack_tag
- urls
e.g.,
```json
{
"body" : {
"type" : "s",
"data" : "Test"
},
"message" : {
"type" : "s",
"data" : "<b>Test</b>\nTest"
},
"summary" : {
"type" : "s",
"data" : "Test"
},
"appname" : {
"type" : "s",
"data" : "TestingtonMcTestles"
},
"category" : {
"type" : "s",
"data" : ""
},
"default_action_name" : {
"type" : "s",
"data" : "default"
},
"icon_path" : {
"type" : "s",
"data" : ""
},
"id" : {
"type" : "i",
"data" : 2
},
"timestamp" : {
"type" : "x",
"data" : 159863270957
},
"timeout" : {
"type" : "x",
"data" : 5000
},
"progress" : {
"type" : "i",
"data" : -1
},
"urgency" : {
"type" : …
```
=> Add env vars to dunstctl history, resolve #1425

src/dbus.c, src/draw.c, src/dunst.c, src/icon-lookup.c, src/icon.c, src/log.c, src/markup.c, src/menu.c, src/notification.c, src/notification.h, src/option_parser.c, src/queues.c, src/queues.h, src/rules.c, src/settings.c, src/wayland/foreign_toplevel.c, src/wayland/wl.c, src/x11/screen.c, src/x11/x.c, test/dbus.c, test/notification.c, test/option_parser.c, test/queues.c, test/setting.c
=> Fix some warnings (gint formatting, size_t/int mix, etc)

test/dbus.c
Self-explanatory; added three assertions to test for values for the properties `urgency`, `stack_tag`, and `urls` are being outputted via `dunstctl history`
=> Add tests for additions in #1426

dunstify.c
not tested properly but should work
=> Use properties instead of private fields in dunstify

completions/_dunstctl.zshcomp, src/dbus.c, src/draw.c, src/dunst.c, src/dunst.h, src/log.h, src/queues.c, src/queues.h, src/settings.c, test/setting.c
fix dbus signal for reload and reload handling.
also quick fix for gradient sizing
=> Fix dbus signal and gradient

Makefile
Add quotes to the VERSION variable, when they are determined by invoking git. git describe doesn't seem to output spaces. But the fallback case of just echoing the VERSION variable may contain spaces, as every release includes a space separated release date in the version variable.
This fixes the issue that if the .git directory is present on a release, but the git command isn't available or fails, the VERSION variable isn't escaped anymore and the release date contained causes a build failure.
=> makefile: add version variable quotes in git case

.gitignore, Makefile, README.md, docs/dunst.1.pod.in, docs/meson.build, dunst.systemd.service.in, meson.build, meson_options.txt, org.knopwob.dunst.service.in, src/meson.build, src/wayland/protocols/meson.build, test/meson.build
Currently, this has no support for the following features  that already existed within Makefile:
* ~~Valgrind~~ https://mesonbuild.com/Unit-tests.html#other-test-options
* ~~Test program~~  `ninja -C build test`
* ~~Documentation (#1225)~~
* Doxygen
Fixes #1224
=> initial meson move

src/output.c
Fixes #1134. Makes it consistent with the wayland output (which will also die when it can't be found) and removes the noise caused by dumping core.
=> output: die instead of dumping core with no X11 output

.editorconfig, .editorconfig-checker.json, .github/workflows/main.yml, HACKING.md, Makefile, completions/_dunstctl.zshcomp, completions/dunst.bashcomp, contrib/notification-history.sh, docs/dunst.1.pod.in, docs/dunst.5.pod, src/input.h, src/settings.h, src/wayland/wl.c, test/draw.c, test/functional-tests/test.sh, test/test-install.sh
Add an `.editorconfig` mostly trying to match the current styles used in the repository. Consistently indented inconsistent files and moved relevant source files to use spaces instead of tabs. Added necessary checking to the CI using `editorconfig-checker`. As it doesn't support "fancy indentations" (e.g. align arguments), the indentation check was disabled.
Fixes #1455
=> Add an .editorconfig file

.editorconfig, Makefile, docs/meson.build, meson.build, src/dunst.c
=> Fix meson configuration files

src/dbus.c
Hello!
We are casually auditing some open-source projects we are using and we found this straightforward use-after-free vulnerability.
When a `get_rule` fails and returns `NULL`, the `name` is free()-ed (line 631) but soon reused for logging (line 638), which is dangerous. This patch fixes this by always free-ing the variable only if it is no longer used.  Even if `get_rule` will unlikely fail at this moment, this patch enhances the code to avoid potential misuse in the future.
Thanks for the brilliant project anyway!
=> Fix a Use-After-Free issue
