dunst-project/dunst

settings.c
Signed-off-by: Anton Löfgren <anton.lofgren@gmail.com>
=> settings: Trivial typo fix on format option description

docs/dunst.pod
There's a lot of open issues regarding this, because the only source of information on this is a comment on an issue which isn't that easy to find.
Add the information to the man page. Let me know if you'd like to see something else mentioned.
=> Document actions and how to interact with them

src/dbus.c
Is there a coding styleguide for this project?
IMO readability goes over linelength here.
=> improve readability in dbus.c

src/notification.c
small indentation and typo correction in dunst print
=> fix typos and reformat print output

src/settings.c
This does basically, what's discussed in #170
=> change order of option_get_* to be displayed during --help

src/notification.c
=> Update notification attributes upon direct replace

config.def.h
=> Change default icons to match freedesktop spec

src/queues.c
Introduced as #379 and #391 got merged in parallel.
Fixes #398
=> Fixup fields to count in monotonic usec time

dunstify.c
I don't know why I actually have made this, but I found it in my stash right now. At some point I have looked into the sources of dunstify.
=> Align columns in dunstify option list

src/dbus.c, src/dbus.h, src/dunst.c, src/notification.c, src/notification.h, src/queues.c, src/queues.h, src/rules.c, src/rules.h, src/settings.c, src/x11/x.c, test/notification.c
Use enums for close reasons and also consistently for urgencies.
=> Use more enums

src/queues.c
So, these would be my two cents for these queue problems. (#431 yet to handle somewhere else)
Fixes #438 
Fixes #427
=> Duplicate notifications

src/dbus.c, src/dunst.c, src/dunst.h, src/menu.c, src/notification.c, src/notification.h, src/option_parser.c, src/queues.h, src/settings.c, src/utils.c, src/utils.h, src/x11/screen.c, src/x11/x.c, src/x11/x.h
Style, Indentation and whitespace changes.
Split into topical commits. -> reviewed with ease commit by commit
=> Style adaptions

src/dbus.c
=> Pack FDN specific names into macro

src/dbus.c
When the DBus name lost function is called, either the whole DBus
connection is lost, or another rivaling FDN daemon acquired the name.
Without enough experience, this is impossible to trace back and examine
further.
To make it easier for new users, dunst prints out the PID of the
process, which currently acquired the FDN DBus name.
Fixes: #458
=> Output the PID of the current FDN daemon

src/settings.c
=> Interpret - as STDIN config file

src/dbus.c
I had been a bit harsh in my IRC memo (dunst-project/dunst-project.org#8). I'm sorry for this.
There's a cosmetic change, which _could_ improve this error message.
=> Improve wording of DBus name lost error message

src/icon.c
As the get_pixbuf_from_file should retrieve a file's content, it
shouldn't fail silently, if the file isn't there.
For codepaths, which don't use the `icon_path` to search for a given
icon, it gives a clearer error message.
Also make it clear that the file should be actually readable when given as a parameter.
This resolves the indifferent error messages from #526.
=> Better warnings for failed icons

src/dbus.h, src/dunst.h, src/log.h, src/markup.c
This fixes minor stuff that I came across while refamiliarizing myself with the code and running clangs scan-build over it.
=> Random fixes

src/dbus.c, src/menu.c, src/notification.c, src/notification.h, src/option_parser.c, src/queues.c, src/settings.c, src/settings.h, src/utils.c, src/utils.h, test/data/test-ini, test/notification.c, test/option_parser.c, test/utils.c
Create a refcounting mechanism for notifications and "lock" them while displayed in dmenu.
Fixes #456
=> Threaded dmenu

src/menu.c
Also changes a type and variable name or two.
I noticed the codebase inconsistently uses bool / gboolean but since bool is used for is_initialized, I stuck to that.
=> Add error message for failed regex initialization

src/markup.c, test/markup.c
Automatically detect and escape invalid and unsupported & entities.
Fixes #546
=> Implement smarter markup escaping

src/markup.c, src/markup.h, src/utils.c, src/utils.h, test/utils.c
Adds docstrings and also assertions to the string replacements in the markup and utils functions.
=> Add docstrings to the functions in markup and utils

config.h, src/dbus.c, src/draw.c, src/dunst.h, src/markup.h, src/notification.c, src/notification.h, src/rules.c, src/settings.c, src/settings.h, src/x11/x.c, src/x11/x.h
Next PR today :wink: 
Well, this mainly removes the clumsy colors array and uses a proper struct for the notification's colors.
=> Notification colors

test/dbus.c
Add some tests for the raw icon assembly. I'm currently working on #571 and finally understand how the pixbuf format is assembled.
So this test is now a low hanging fruit and will be later necessary.
=> Test raw icon assembly in DBus

src/icon.c
As already noted in the code comment, we all knew that the in memory
conversion to a PNG stream is a cumbersome technique. But it was worth
to remove the GTK dependency.
After finding out, that gdk_pixbuf_new_from_data can actually use a
GVariant and share its memory without allocating new memory, I poked
the cairo docs for a similar technique.
There is cairo_image_surface_create_for_data, which would achieve the
same, but cairo uses another color byte order. So we have to manually
copy and reassemble the bytes.
It may look like a big rise in complexity, but actually, it's straight
forward.
And the gdk_pixbuf_to_cairo_surface is 33x faster.
=> Manually convert GdkPixbuf to cairo surfaces

config.h, src/dbus.c, src/draw.c, src/icon.c, src/log.c, src/markup.c, src/menu.c, src/notification.c, src/option_parser.c, src/option_parser.h, src/queues.c, src/settings.c, src/settings.h, src/utils.c, src/utils.h, src/x11/screen.c, src/x11/x.c
Ok, this is the first part for #412 
It introduces string parsers with a uniform signature with a `bool` return value. This `bool` return value enhances the functions to state a fail. And enables the program to get rid of the "default" value in the parser.
=> Settings (part 1/x)

src/x11/screen.c
=> Harden against undefined X Atoms

Makefile, README.md, config.mk
I've just read https://danyspin97.org/blog/makefiles-best-practices/ and applied it to our `Makefile`.
=> Improve makefile 

.circleci/config.yml, .travis.yml, test/test-install.sh
Ensure that dunst is installed correctly to avoid bugs like #601.
=> Test installation

HACKING.md, src/dbus.c, src/icon.h, src/markup.c, src/menu.h, src/queues.c, src/queues.h, src/x11/screen.h
I've found the `@retval` directive in the doxygen doc. Nice thing
=> Use @retval in codedocs

Makefile, test/test-install.sh
Put dunstify in $PATH, so you can run it easily without manually moving files, like dunst itself
=> Install dunstify

src/x11/x.c
=> No compositor if no _NET_WM_CM_Si atom

src/notification.c, src/notification.h, src/rules.c
I have noticed that when multiple rules match only one script gets called. So i changed `script` to an array and store all the scripts in there where the rule matches.
I don't usually work with c so i am not sure if the use of `g_renew` is correct here.
=> multiple scripts for notification

dunstify.c
=> Do not accept empty appname argument

src/x11/screen.c
- Get the window with keyboard focus using XGetInputFocus() instead of
_NET_ACTIVE_WINDOW
- Handle edge cases of keyboard/mouse focus being on different X screen
- Set sane default in case the active monitor can't be determined
(fixing issue #762)
=> Fix process of gettign the active monitor

Makefile, README.md
@hackedWifi
Fixes indent in makefile and improves README wording.
Fixes #824
=> Improve support for compiling without wayland

src/settings.c
=> Fix background and highlight rules not working

.github/workflows/main.yml, README.md, config.mk
This should fix dunst-project/docker-images#4
=> Add CFLAGS with -Werror for CI

src/wayland/wl.c
=> wl.c: Fix segfault on shutdown

src/draw.c
=> draw: fix alignment not using the right width

README.md, docs/dunst.5.pod, src/settings_data.h, src/utils.c
=> Add keyboard shorcuts again, now in the global section

src/dunst.c, src/queues.c, src/queues.h, test/input.c, test/queues.c
=> Fix notifications sometimes not disappearing

src/utils.c
Hey there, 
This pull request fixes a small typo I encountered when setting up dunst :)
=> Fix a typo in deprecated_sections_message

README.md
=> [readme] fix github wrongly applying MathML

docs/dunst.5.pod
=> docs: fix typo

Makefile, test/draw.c
Also stop the makefile if neither X11 or WAYLAND are set
=> Fix test when building wayland only

dunstrc
Fix some misspellings in the example configuration file.
=> Fix some misspellings

docs/dunst.5.pod, dunstrc
=> Update title/class docs

Makefile, test/test.c
Should resolve the issues pointed by @zappolowski in #1373
=> Use TESTDIR env var

src/notification.c
=> Open url if no action is present

dunstify.c, src/dbus.c
=> Fix dunstify icon and ids
